image: node:alpine
# image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - test-e2e

before_script:
  - npm ci

unit_integration_tests:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script: npm run build
