image: node:alpine
# image: node:latest

variables:
  npm_config_cache: /builds/sargalias/gitlab-ci-config/.npm
  CYPRESS_CACHE_FOLDER: /builds/sargalias/gitlab-ci-config/cache/Cypress

cache:
  paths:
    - .npm
    - cache/Cypress

stages:
  - test
  - build
  - test-e2e

before_script:
  - npm ci

unit_integration_tests:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script: npm run build
